# Generated by Django 3.2.4 on 2021-07-03 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('telefone', models.IntegerField(default='0')),
                ('password', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Utilizadores',
                'db_table': 'utilizador',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('utilizadorid', models.OneToOneField(db_column='UtilizadorID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Utilizadores.utilizador')),
            ],
            options={
                'db_table': 'Administrador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('utilizadorid', models.OneToOneField(db_column='UtilizadorID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Utilizadores.utilizador')),
            ],
            options={
                'db_table': 'Participante',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proponente',
            fields=[
                ('utilizadorid', models.OneToOneField(db_column='UtilizadorID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Utilizadores.utilizador')),
            ],
            options={
                'db_table': 'Proponente',
                'managed': True,
            },
        ),
    ]
