# Generated by Django 3.2.4 on 2021-07-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilizadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='TipoUtilizador',
            field=models.CharField(choices=[('Participante', 'Participante'), ('Administrador', 'Administrador'), ('Proponente', 'Proponente')], default='Participante', max_length=30),
        ),
    ]
