# Generated by Django 3.2.4 on 2021-06-08 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=255, null=True, unique=True)),
                ('morada', models.CharField(blank=True, db_column='Morada', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Campus',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Recurso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Recurso_estado',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('Estado', models.CharField(blank=True, db_column='Estado', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Recurso_estado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoDeRecurso',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.IntegerField(blank=True, db_column='Nome', null=True, unique=True)),
            ],
            options={
                'db_table': 'Tipo de recurso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('recursoid', models.OneToOneField(db_column='RecursoID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Recurso.recurso')),
            ],
            options={
                'db_table': 'Equipamento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Serviço',
            fields=[
                ('recursoid', models.OneToOneField(db_column='RecursoID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Recurso.recurso')),
            ],
            options={
                'db_table': 'Serviço',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='recurso',
            name='estado',
            field=models.ForeignKey(db_column='Estado', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Recurso.recurso_estado'),
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=255, null=True, verbose_name='Edificio')),
                ('campusid', models.ForeignKey(db_column='CampusID', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Recurso.campus', verbose_name='Campus')),
            ],
            options={
                'db_table': 'Edificio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('recursoid', models.OneToOneField(db_column='RecursoID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Recurso.recurso', verbose_name='Sala')),
                ('lugares', models.IntegerField(blank=True, db_column='Lugares', null=True)),
                ('edificioid', models.ForeignKey(db_column='EdificioID', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Recurso.edificio')),
            ],
            options={
                'db_table': 'Sala',
                'managed': True,
            },
        ),
    ]
