# Generated by Django 3.2 on 2021-05-06 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=255, null=True, unique=True)),
                ('morada', models.CharField(blank=True, db_column='Morada', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Campus',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=255, null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Recurso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoDeEquipamento',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.IntegerField(blank=True, db_column='Nome', null=True, unique=True)),
            ],
            options={
                'db_table': 'Tipo de equipamento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoDeRecurso',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.IntegerField(blank=True, db_column='Nome', null=True, unique=True)),
            ],
            options={
                'db_table': 'Tipo de recurso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoDeServiço',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.IntegerField(blank=True, db_column='Nome', null=True, unique=True)),
            ],
            options={
                'db_table': 'Tipo de serviço',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=255, null=True)),
                ('campusid', models.ForeignKey(db_column='CampusID', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Recurso.campus')),
            ],
            options={
                'db_table': 'Edificio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Serviço',
            fields=[
                ('recursoid', models.OneToOneField(db_column='RecursoID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Recurso.recurso')),
                ('tipo_de_serviçoid', models.ForeignKey(db_column='Tipo de serviçoID', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Recurso.tipodeserviço')),
            ],
            options={
                'db_table': 'Serviço',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('recursoid', models.OneToOneField(db_column='RecursoID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Recurso.recurso')),
                ('lugares', models.IntegerField(blank=True, db_column='Lugares', null=True)),
                ('edificioid', models.ForeignKey(db_column='EdificioID', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Recurso.edificio')),
            ],
            options={
                'db_table': 'Sala',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('recursoid', models.OneToOneField(db_column='RecursoID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Recurso.recurso')),
                ('tipo_de_equipamentoid', models.ForeignKey(db_column='Tipo de equipamentoID', on_delete=django.db.models.deletion.DO_NOTHING, to='Recurso.tipodeequipamento')),
            ],
            options={
                'db_table': 'Equipamento',
                'managed': True,
            },
        ),
    ]
