# Generated by Django 3.2.3 on 2021-05-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evento', '0003_auto_20210530_1534'),
        ('Recurso', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='tipo_de_equipamentoid',
        ),
        migrations.RemoveField(
            model_name='serviço',
            name='tipo_de_serviçoid',
        ),
        migrations.AlterField(
            model_name='tipoderecurso',
            name='nome',
            field=models.CharField(blank=True, db_column='Nome', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='TipoDeEquipamento',
        ),
        migrations.DeleteModel(
            name='TipoDeServiço',
        ),
    ]
