# Generated by Django 3.2.4 on 2021-06-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recurso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoderecurso',
            name='nome',
            field=models.CharField(blank=True, db_column='Nome', max_length=255, null=True, unique=True),
        ),
    ]
