# Generated by Django 3.2.3 on 2021-05-30 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recurso', '0002_auto_20210530_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso_estado',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('Estado', models.CharField(blank=True, db_column='Estado', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Recurso_estado',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='recurso',
            name='estado',
            field=models.ForeignKey(db_column='Estado', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Recurso.recurso_estado'),
        ),
    ]
