# Generated by Django 3.2.4 on 2021-06-29 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('remetente', models.CharField(blank=True, db_column='Remetente', max_length=255, null=True)),
                ('receptor', models.CharField(blank=True, db_column='Receptor', max_length=255, null=True)),
                ('conteúdo', models.CharField(blank=True, db_column='Conteúdo', max_length=255, null=True)),
                ('data', models.DateField(blank=True, db_column='Data', null=True)),
                ('assunto', models.CharField(blank=True, db_column='Assunto', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Mensagem',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=255, null=True)),
                ('email', models.CharField(db_column='Email', max_length=255, null=True, unique=True)),
                ('telefone', models.CharField(blank=True, db_column='Telefone', max_length=255, null=True)),
                ('username', models.CharField(db_column='Username', max_length=255, null=True, unique=True)),
                ('password', models.CharField(db_column='Password', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Utilizador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('utilizadorid', models.OneToOneField(db_column='UtilizadorID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.utilizador')),
            ],
            options={
                'db_table': 'Administrador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('utilizadorid', models.OneToOneField(db_column='UtilizadorID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.utilizador')),
            ],
            options={
                'db_table': 'Participante',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proponente',
            fields=[
                ('utilizadorid', models.OneToOneField(db_column='UtilizadorID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.utilizador')),
            ],
            options={
                'db_table': 'Proponente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UtilizadorMensagem',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('mensagemid', models.ForeignKey(db_column='MensagemID', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.mensagem')),
                ('utilizadorid', models.ForeignKey(db_column='UtilizadorID', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.utilizador')),
            ],
            options={
                'db_table': 'Utilizador_Mensagem',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='mensagem',
            name='utilizadorid',
            field=models.ForeignKey(db_column='UtilizadorID', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.utilizador'),
        ),
    ]
