# Generated by Django 3.2.2 on 2021-05-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='email',
            field=models.CharField(db_column='Email', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='password',
            field=models.CharField(db_column='Password', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='username',
            field=models.CharField(db_column='Username', max_length=255, null=True, unique=True),
        ),
    ]
