# Generated by Django 3.2 on 2021-05-06 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Evento', '0001_initial'),
        ('main', '0002_auto_20210506_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscrição',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('utilizador_eventoid', models.IntegerField(db_column='Utilizador_EventoID')),
                ('checkin', models.IntegerField(db_column='CheckIn')),
                ('valido', models.IntegerField(db_column='Valido')),
                ('eventoid', models.ForeignKey(db_column='EventoID', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Evento.evento')),
                ('participanteutilizadorid', models.ForeignKey(db_column='ParticipanteUtilizadorID', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.participante')),
            ],
            options={
                'db_table': 'Inscrição',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('divida', models.FloatField(db_column='Divida')),
                ('data', models.DateField(blank=True, db_column='Data', null=True)),
                ('hora', models.TimeField(blank=True, db_column='Hora', null=True)),
                ('inscriçãoid', models.ForeignKey(db_column='InscriçãoID', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inscriçao.inscrição')),
            ],
            options={
                'db_table': 'Pagamento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('inscriçãoid', models.ForeignKey(db_column='InscriçãoID', on_delete=django.db.models.deletion.DO_NOTHING, to='Inscriçao.inscrição')),
            ],
            options={
                'db_table': 'Feedback',
                'managed': True,
            },
        ),
    ]
