# Generated by Django 3.2.2 on 2021-05-14 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inscriçao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscrição',
            name='utilizador_eventoid',
        ),
    ]
