# Generated by Django 3.2.3 on 2021-05-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inscriçao', '0002_remove_inscrição_utilizador_eventoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscrição',
            name='checkin',
            field=models.BooleanField(db_column='CheckIn'),
        ),
        migrations.AlterField(
            model_name='inscrição',
            name='valido',
            field=models.BooleanField(db_column='Valido'),
        ),
    ]
