# Generated by Django 3.2.3 on 2021-05-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formulario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='temporario',
            field=models.BooleanField(db_column='temporario', default=False),
        ),
    ]
