# Generated by Django 3.2.4 on 2021-06-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formulario', '0002_formuláriopergunta_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulário',
            name='publico',
            field=models.BooleanField(db_column='Publico'),
        ),
    ]
