# Generated by Django 3.2.4 on 2021-07-04 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Evento', '0003_auto_20210704_1514'),
        ('Formulario', '0002_auto_20210704_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulário',
            name='evento_id',
            field=models.ForeignKey(blank=True, db_column='Evento', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Evento.evento'),
        ),
    ]
