# Generated by Django 3.2.4 on 2021-06-22 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Evento', '0002_initial'),
        ('Formulario', '0003_alter_formulário_publico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulário',
            name='tipo_de_eventoid',
            field=models.ForeignKey(blank=True, db_column='Tipo de eventoID', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Evento.tipodeevento'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='numero_maximo_de_escolhas',
            field=models.IntegerField(db_column='NumeroMaximoDeEscolhas', default=None, null=True),
        ),
    ]
