# Generated by Django 3.2.4 on 2021-07-05 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Formulario', '0003_formulário_evento_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formuláriopergunta',
            name='pos',
            field=models.IntegerField(db_column='Pos', default=0, null=True, verbose_name=django.db.models.deletion.SET_NULL),
        ),
    ]
