# Generated by Django 3.2.4 on 2021-06-24 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Formulario', '0004_auto_20210622_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formuláriopergunta',
            name='formulárioid',
            field=models.OneToOneField(db_column='FormulárioID', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Formulario.formulário'),
        ),
    ]
