# Generated by Django 3.2.4 on 2021-06-27 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Formulario', '0007_auto_20210624_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formuláriopergunta',
            name='formulárioid',
            field=models.ForeignKey(db_column='FormulárioID', on_delete=django.db.models.deletion.CASCADE, to='Formulario.formulário'),
        ),
        migrations.AlterField(
            model_name='formuláriopergunta',
            name='perguntaid',
            field=models.ForeignKey(db_column='PerguntaID', on_delete=django.db.models.deletion.CASCADE, to='Formulario.pergunta'),
        ),
    ]
