# Generated by Django 3.2.4 on 2021-06-29 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Recurso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoDeParticipação',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome_evento', models.CharField(blank=True, db_column='Nome evento', max_length=255, null=True)),
                ('data_emissão', models.DateField(blank=True, db_column='Data emissão', null=True)),
                ('nome_participante', models.CharField(blank=True, db_column='Nome participante', max_length=255, null=True)),
                ('publico', models.IntegerField(db_column='Publico')),
            ],
            options={
                'db_table': 'Certificado de Participação',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=255, null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', default='Não submetido', max_length=255, null=True)),
                ('descrição', models.CharField(blank=True, db_column='Descrição', max_length=255, null=True)),
                ('data', models.DateField(blank=True, db_column='Data', null=True)),
                ('hora', models.TimeField(blank=True, db_column='Hora', null=True)),
                ('duração', models.IntegerField(blank=True, db_column='Duração', null=True)),
                ('valor', models.FloatField(db_column='Valor')),
                ('evento_pagoid', models.IntegerField(db_column='Evento pagoID')),
            ],
            options={
                'db_table': 'Evento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoDeEvento',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Tipo de evento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Requisição',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('dia_inicial', models.DateField(blank=True, db_column='Dia inicial', null=True)),
                ('hora_inicial', models.TimeField(blank=True, db_column='Hora inicial', null=True)),
                ('dia_final', models.DateField(blank=True, db_column='Dia final', null=True)),
                ('hora_final', models.TimeField(blank=True, db_column='Hora final', null=True)),
                ('eventoid', models.OneToOneField(db_column='EventoID', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Evento.evento')),
                ('recursoid', models.OneToOneField(db_column='RecursoID', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Recurso.recurso')),
            ],
            options={
                'db_table': 'Requisição',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PedidoDeRecurso',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(db_column='Quantidade')),
                ('dia_inicial', models.DateField(blank=True, db_column='Dia inicial', null=True)),
                ('hora_inicial', models.TimeField(blank=True, db_column='Hora inicial', null=True)),
                ('dia_final', models.DateField(blank=True, db_column='Dia final', null=True)),
                ('hora_final', models.TimeField(blank=True, db_column='Hora final', null=True)),
                ('capacidade', models.IntegerField(blank=True, db_column='Capacidade', null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', default='Não submetido', max_length=255, null=True)),
                ('eventoid', models.ForeignKey(db_column='EventoID', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Evento.evento')),
                ('tipo_de_recursoid', models.ForeignKey(db_column='Tipo de recursoID', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Recurso.tipoderecurso')),
            ],
            options={
                'db_table': 'Pedido de recurso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EventoServicos',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('eventoId', models.ForeignKey(db_column='Evento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Evento.evento')),
                ('servicoId', models.ForeignKey(db_column='Servico', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Recurso.serviço')),
            ],
        ),
        migrations.CreateModel(
            name='EventoLocais',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('eventoId', models.ForeignKey(db_column='Evento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Evento.evento')),
                ('localId', models.ForeignKey(db_column='Local', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Recurso.sala')),
            ],
        ),
        migrations.CreateModel(
            name='EventoEquipamentos',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('equipamentoId', models.ForeignKey(db_column='Equipamento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Recurso.equipamento')),
                ('eventoId', models.ForeignKey(db_column='Evento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Evento.evento')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='equipamentos',
            field=models.ForeignKey(db_column='equipamentos', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Evento.eventoequipamentos'),
        ),
    ]
