# Generated by Django 3.2.4 on 2021-06-29 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Evento', '0001_initial'),
        ('main', '0001_initial'),
        ('Formulario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='formuláriofeedbackid',
            field=models.ForeignKey(db_column='FormulárioFeedbackID', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='Formulario.formulário'),
        ),
        migrations.AddField(
            model_name='evento',
            name='formulárioinscriçãoid',
            field=models.ForeignKey(db_column='FormulárioInscriçãoID', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Formulario.formulário'),
        ),
        migrations.AddField(
            model_name='evento',
            name='locais',
            field=models.ForeignKey(db_column='locais', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Evento.eventolocais'),
        ),
        migrations.AddField(
            model_name='evento',
            name='proponenteutilizadorid',
            field=models.ForeignKey(db_column='ProponenteUtilizadorID', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.proponente'),
        ),
        migrations.AddField(
            model_name='evento',
            name='servicos',
            field=models.ForeignKey(db_column='servicos', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Evento.eventoservicos'),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo_de_eventoid',
            field=models.ForeignKey(db_column='Tipo de eventoID', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Evento.tipodeevento'),
        ),
    ]
