# Generated by Django 3.2 on 2021-05-13 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evento', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificadodeparticipação',
            name='eventoid',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='formuláriofeedbackid',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='formulárioinscriçãoid',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='proponenteutilizadorid',
        ),
        migrations.RemoveField(
            model_name='tipodeevento',
            name='slug',
        ),
    ]
