# Generated by Django 3.2.4 on 2021-07-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evento', '0003_auto_20210704_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='duração',
            field=models.FloatField(blank=True, db_column='Duração', null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='evento_pagoid',
            field=models.IntegerField(db_column='Evento pagoID', default=None),
        ),
    ]
