# Generated by Django 3.2.4 on 2021-07-04 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Evento', '0004_auto_20210704_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='evento_pagoid',
            field=models.IntegerField(db_column='Evento pagoID', default=None, null=True, verbose_name=django.db.models.deletion.SET_NULL),
        ),
    ]
